### ISSUE TITLE
 aergo-iot-microcontrollers

### ISSUE THREAD

**Issue by ghost** [aergoio/aergo-iot-microcontrollers#1] opened 2022-09-20 04:50 UTC
Dear Sir/Madam
Can you explain the methods to send the data between microcontrollers?

**Comment by kroggen** [comment] 2022-09-20 18:03
Hello,

This library is used for the devices to communicate with the blockchain, including smart contracts.

It does not support communication between devices. For this you can use another method, like HTTP, TCP, etc.

**Comment by ghost** [comment] 2022-09-21 04:04
Thank you for your reply. In "iot_receiver_with_actuator.ino" when I try to connect with aergo_connect(&instance,"http://testnet-api.aergo.io:7845"), It post with error "Error connecting to HTTP2 server". I couldn't able to connect to http://testnet-api.aergo.io:7845 which makes unavailability in querying the last state from smart contracts. How could I correct my statement?
"

**Comment by kroggen** [comment] 2022-09-21 07:13
Out testnet was under maintenance in the last hours. Maybe this was the reason. If you deployed some contract, check if it is still there. If not, please deploy again.

We had to exceptionally revert the last part of the test network blockchain due to some problems. This process of reversion does not occur on the mainnet, of course.

If the problem of connection persists after a new test, please inform.

**Comment by ghost** [comment] 2022-09-21 07:26
Still I was facing such issues 
"E (21649) esp-tls: Failed to connnect to host (errno 113)
E (21650) esp-tls: Failed to open new connection
E (21650) sh2lib: [sh2-connect] esp-tls connection failed
Error connecting to HTTP2 server

**Comment by kroggen** [comment] 2022-09-21 17:14
Hmm, maybe you are using a newer version of ESP library. I have not tested with the last ones.
You can get technical support on our Discord channel as well.

**Comment by pmiot** [comment] 2022-09-22 05:35
Thank you for your reply.

**Comment by pmiot** [comment] 2022-09-22 05:54
My version of ESP library is pretty old.


![1](https://user-images.githubusercontent.com/114131882/191668797-fb141828-70ab-45b9-ad30-4f6b3034acb1.png)




Also I have encountered


![2](https://user-images.githubusercontent.com/114131882/191670101-6298bcd4-f1d8-42ff-ab28-04e833f59368.png)

**Comment by kroggen** [comment] 2022-09-22 23:31
The 404 error on the browser is normal.

I tested with libaergo now, and the API is working as expected.

Have you modified your WiFi credentials on the code?

```c
const char* ssid = "<<<include>>>";
const char* password =  "<<<include>>>";
```

I suggest you to start with the [contract_query](https://github.com/aergoio/aergo-iot-microcontrollers/blob/master/espressif-esp32/examples/contract_query/contract_query.ino) example

I am using ESP library 1.0.2, you can start with the same just for testing.

**Comment by pmiot** [comment] 2022-09-23 04:07
Still faced with such error when executing contract_query example

Connecting to WiFi...
Done. Starting HTTP2 connection...
E (19642) esp-tls: Failed to connnect to host (errno 113)
E (19643) esp-tls: Failed to open new connection
E (19643) sh2lib: [sh2-connect] esp-tls connection failed
Error connecting to HTTP2 server

**Comment by kroggen** [comment] 2022-09-24 04:09
I made a new test with a device, and it works. I don't know what is going on on your case

Try with library version 1.0.6

**Comment by pmiot** [comment] 2022-09-24 05:04
I think, initially when I try to compile iot_sender_with_sensor code, I was faced with error "'txn_hash' was not declared in this scope". So I made hash value as NULL.
bool ret = aergo_call_smart_contract(&instance,
        "",
        &account,
        "AmhCzNds4F9i5Duoyai6FfzSiF5Re5PEhcH8kQWkKNbBP5Z4djcX",
        "update_value", "i", value);

Whether this cause any error.

**Comment by kroggen** [comment] 2022-09-24 05:07
No, you should make the simpler example to work first, and it is the `contract_query` example

**Comment by pmiot** [comment] 2022-09-24 07:13
Well I started with "contract_query" example. I have the following error. And this is the complete error for every example. And my library version is 1.0.6.

Connecting to WiFi...
Done. Starting HTTP2 connection...
E (22722) esp-tls: Failed to connect to host (errno 113)
E (22723) esp-tls: Failed to open new connection
E (22723) sh2lib: [sh2-connect] esp-tls connection failed
Error connecting to HTTP2 server

When I try with different aergo_connect address like "https://testnet-algorand.api.purestake.io/..." I received success in connection to host. But I couldn't send any value from that host.

**Comment by kroggen** [comment] 2022-09-24 21:09
Hmm, strange. Maybe your network is blocking the connection?

Could you make a test with [libaergo](https://github.com/aergoio/libaergo)? You will need a Mac or Linux for that though. It can be a VM, like VirtualBox

First follow the instructions to build and install it. Then compile the [contract_query](https://github.com/aergoio/libaergo/tree/master/examples/contract_query) example

Are you able to access https://testnet.aergoscan.io/?

**Comment by pmiot** [comment] 2022-09-26 04:04
Yup I'm able to access https://testnet.aergoscan.io/. But to my knowledge I think libaergo doesn't support microcontrollers like ESP32.

Am I correct with my configurations.

![1](https://user-images.githubusercontent.com/114131882/192202518-201a5e77-8d69-4953-a725-a9404155c478.png)

**Comment by kroggen** [comment] 2022-09-26 06:17
libaergo runs locally on your computer. The suggestion is to check if you can connect to http://testnet-api.aergo.io:7845/ on your network and retrieve content.

I suspect that the connection to that location is slow on your network, and then it fails on [this code](https://github.com/espressif/esp-idf/blob/7ef5fa8a0ab717f676bbb22f3a1ea3c2a15fb249/components/esp-tls/esp_tls.c#L142-L148) and `ret` is lower than zero. Also `cfg` is null so it fails.

This piece of code is not present in newer versions of `esp-idf` and `arduino-esp32`, but this library (aergo-esp32) does not compile on the last version of `arduino-esp32` (2.0.5)

It is interesting that we are using the same code, and it works on the devices I have here but don't work on yours. This is why I think the problem can be on the network. But it is also strange because I am on the opposite side of the planet (comparing to where the http://testnet-api.aergo.io:7845/ host is) and the connection works just fine, even if it is slow.

As I cannot reproduce the error, I cannot help you further than that.

> Note: the code on this library does not use TLS, it uses the `esp_tls` library just to make a normal TCP connection, then it passes that connection to `nghttp2`. TLS is not enabled on http://testnet-api.aergo.io:7845/ this is why it uses http instead of https

**Comment by kroggen** [comment] 2022-09-26 06:25
Oh, I found out that errno 113 = No route to host

Search on the internet for <esp32 errno 113>
You will find a lot of content

**Comment by pmiot** [comment] 2022-09-26 08:16
Did I have create aergo account using docker?

https://aergo.readthedocs.io/en/2.2/using-network/accounts.html

**Comment by kroggen** [comment] 2022-09-26 19:33
Nope.

The place where you would create account depends on the usage / goal.

For yourself, you can use [Aergo Connect](https://chrome.google.com/webstore/detail/aergo-connect/iopigoikekfcpcapjlkcdlokheickhpc?hl=en)

In the ESP32, it creates an account automatically used to send transactions.

For these type of questions, please use our [Discord channel](https://discord.com/channels/491857910285205504/491860868662034438)

If you were able to solve the problem with your ESP32 or your network, please close this issue

**Comment by pmiot** [comment] 2022-09-28 06:45
Thank you for your guidance. Now I'm able to view the balance of the transactions using contract_call.

As you said it is with the problem of wifi network.
There is no close issue button available in comment section.

**Closed as completed** 2022-09-28 17:05 UTC
